# Generated by Django 3.2.7 on 2021-09-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointmentscheduling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentscheduling',
            name='scheduling_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AvailableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hour')),
            ],
        ),
    ]
