# Generated by Django 3.2.7 on 2021-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210912_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableschedule',
            name='hour',
        ),
        migrations.AddField(
            model_name='availableschedule',
            name='hour',
            field=models.ManyToManyField(to='core.Hour'),
        ),
    ]
